# Generated by Django 5.2.4 on 2025-07-21 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Marca de tiempo')),
                ('alarm_type', models.CharField(choices=[('HIGH', 'Valor alto'), ('LOW', 'Valor bajo'), ('QUALITY', 'Calidad'), ('COMMUNICATION', 'Comunicación'), ('SYSTEM', 'Sistema')], max_length=20, verbose_name='Tipo de alarma')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10, verbose_name='Severidad')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Valor que causó la alarma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Reconocida')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconocida en')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='Aclarada en')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reconocida por')),
            ],
            options={
                'verbose_name': 'Alarma',
                'verbose_name_plural': 'Alarmas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Marca de tiempo')),
                ('action', models.CharField(max_length=100, verbose_name='Acción')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del objeto')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Representación del objeto')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Marca de tiempo')),
                ('event_type', models.CharField(choices=[('CONNECT', 'Conexión'), ('DISCONNECT', 'Desconexión'), ('ERROR', 'Error'), ('RECONNECT', 'Reconexión')], max_length=20, verbose_name='Tipo de evento')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('error_code', models.IntegerField(blank=True, null=True, verbose_name='Código de error')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Tiempo de respuesta (ms)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Conexión',
                'verbose_name_plural': 'Logs de Conexión',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OpcUaServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del servidor')),
                ('endpoint_url', models.URLField(verbose_name='URL del endpoint')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contraseña')),
                ('security_mode', models.CharField(choices=[('NONE', 'Sin seguridad'), ('SIGN', 'Solo firma'), ('SIGN_ENCRYPT', 'Firma y encriptación')], default='NONE', max_length=20, verbose_name='Modo de seguridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Servidor OPC-UA',
                'verbose_name_plural': 'Servidores OPC-UA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpcUaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=200, verbose_name='Node ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la variable')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('data_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('INTEGER', 'Entero'), ('FLOAT', 'Decimal'), ('STRING', 'Texto'), ('DATETIME', 'Fecha y hora')], max_length=20, verbose_name='Tipo de dato')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valor mínimo')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valor máximo')),
                ('is_writable', models.BooleanField(default=False, verbose_name='Es escribible')),
                ('is_monitored', models.BooleanField(default=True, verbose_name='Es monitorizada')),
                ('sampling_interval', models.IntegerField(default=1000, verbose_name='Intervalo de muestreo (ms)')),
                ('alarm_enabled', models.BooleanField(default=False, verbose_name='Alarmas habilitadas')),
                ('alarm_high_limit', models.FloatField(blank=True, null=True, verbose_name='Límite alto de alarma')),
                ('alarm_low_limit', models.FloatField(blank=True, null=True, verbose_name='Límite bajo de alarma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.opcuaserver', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Variable OPC-UA',
                'verbose_name_plural': 'Variables OPC-UA',
                'ordering': ['server', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clave')),
                ('value', models.TextField(verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('value_type', models.CharField(choices=[('STRING', 'Texto'), ('INTEGER', 'Entero'), ('FLOAT', 'Decimal'), ('BOOLEAN', 'Booleano'), ('JSON', 'JSON')], default='STRING', max_length=20, verbose_name='Tipo de valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='VariableReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Marca de tiempo')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Valor boolean')),
                ('value_integer', models.BigIntegerField(blank=True, null=True, verbose_name='Valor entero')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='Valor decimal')),
                ('value_string', models.TextField(blank=True, null=True, verbose_name='Valor texto')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Valor fecha')),
                ('quality', models.CharField(choices=[('GOOD', 'Buena'), ('BAD', 'Mala'), ('UNCERTAIN', 'Incierta')], default='GOOD', max_length=20, verbose_name='Calidad')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Código de estado')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='main_app.opcuavariable', verbose_name='Variable')),
            ],
            options={
                'verbose_name': 'Lectura de Variable',
                'verbose_name_plural': 'Lecturas de Variables',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Variable',
                'verbose_name_plural': 'Tipos de Variables',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_level',
            field=models.CharField(choices=[('VIEWER', 'Solo lectura'), ('OPERATOR', 'Operador'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administrador')], default='VIEWER', max_length=20, verbose_name='Nivel de acceso'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notificaciones por email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actividad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='connectionlog',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='main_app.opcuaserver', verbose_name='Servidor'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='main_app.opcuavariable', verbose_name='Variable'),
        ),
        migrations.AddField(
            model_name='opcuavariable',
            name='variable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.variabletype', verbose_name='Tipo de variable'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddIndex(
            model_name='variablereading',
            index=models.Index(fields=['variable', '-timestamp'], name='main_app_va_variabl_13c950_idx'),
        ),
        migrations.AddIndex(
            model_name='variablereading',
            index=models.Index(fields=['timestamp'], name='main_app_va_timesta_913e9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opcuavariable',
            unique_together={('server', 'node_id')},
        ),
    ]
